AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/NilComparison:
  Enabled: false

Naming/MethodName:
  Exclude:
    - "lib/delivered/types.rb"

Layout/LineLength:
  Max: 100

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
